from enum import Enum


class WindowTitle(Enum):
    CLASSROOM = "Tutor.com Classroom"
    PUBLIC_CHAT = "Public Chat"
    EDITOR = "Editor"
    SERVER_CONNECTION_ERROR = "Could Not Connect To Server"
    WHITEBOARD = "Whiteboard"
    GRAPHING_CALCULATOR = "Graphing Calculator"
    WORD_PROCESSOR = "Word Processor"
    C_LIKE_EDITOR = "C-Like Editor"
    CSS_EDITOR = "CSS Editor"
    GO_EDITOR = "Go Editor"
    HTML_EDITOR = "HTML Editor"
    JAVA_EDITOR = "Java Editor"
    JAVASCRIPT_EDITOR = "JavaScript Editor"
    MATHEMATICA_EDITOR = "Mathematica Editor"
    PHP_EDITOR = "PHP Editor"
    PYTHON_EDITOR = "Python Editor"
    R_EDITOR = "R Editor"
    RUBY_EDITOR = "Ruby Editor"
    SCREENSHARE = "Screenshare"
    SQL_EDITOR = "SQL Editor"
    XML_EDITOR = "XML Editor"
